# Generated by Django 5.2.8 on 2025-11-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_closed_at_ticket_closed_by_ticket_reopened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, help_text='Short sequential ticket number', null=True, unique=True),
        ),
    ]
